### ISSUE TITLE
Better recipes for bread block

### ISSUE THREAD

**Issue by macks2008** [HexxyCraft/modpack#150]
![image](https://github.com/HexxyCraft/modpack/assets/7110033/15c280eb-28f2-4a37-bb6b-97dd6b846ae0)
There is no conversion back from this, and it doesn't make a whole lot of sense in the first place. I think it would make more sense as just a storage block for bread, but the current recipe each block is equivalent to the cost of one bread (and some string, because unbundled  haybale != vanilla haybale).
My suggestion would be 9 bread = 1 bread block = 9 bread, and get rid of this recipe since it would become OP. 
~~Relatedly, unbundled haybale should probably be able to convert directly back to wheat without needing to add string.~~

**Comment by macks2008** [comment]
I think I can PR this if you want.

**Comment by object-Object** [comment]
Please feel free, PRs are *always* encouraged here!

**Comment by macks2008** [comment]
Okay nevermind my remark about "Relatedly, unbundled haybale should probably be able to convert directly back to wheat without needing to add string.". Turns out, I might be an idiot, Convenient Decor already adds an unbundled-uncrafting recipe.

I thought it didn’t because of something LlamaLord said (which is ironic in context), but never actually checked :skull:

I still have a possible follow-up enhancement, relating to unifying all of these architectural blocks, but one PR at a time.

On the upside, I'm ready to do the PR. Look for it within the hour, unless I get sidetracked again.
