### ISSUE TITLE
Add RAT's Mischief

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#160]
https://modrinth.com/mod/rats-mischief

**Comment by LlamaSageR** [comment]
A good mod, but not a good fit for the current world. Requires loot from Ancient Cities for progression, which is challenging given the age. Furthermore, while the rats are very funny and have interesting possibilities, it doesn't contribute much functionality that is needed to the server. More content, but not to much of an end. Not to mention the hundreds of rats is likely *incredibly* detrimental to server performance. If we move on to a new world at some point, RAT's Mischief will definitely be a consideration.
