### ISSUE TITLE
Add Sandwichable

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#161]
https://www.curseforge.com/minecraft/mc-mods/sandwichable

**Comment by walksanatora** [comment]
sub sandwich sandwich (too bad i cant make a sub sandwich sandwich sandwich)
but i did once try a sub sandwich sandwich when in SP with the bc23 pack and it *did* close my client (mabey a crash idk i forgot about it, mabey it was cause i stacked too tall)

**Comment by LlamaSageR** [comment]
Given the issue of "Promoting Food Diversity," adding an objectively best option seems unwise. Not to mention the ability to put potions inside the sandwiches, something I recall seeing in other modpacks via Create.
