### ISSUE TITLE
Packwiz installs old version of Xaero's Minimap/Worldmap, manually updating causes crash

### ISSUE THREAD

**Issue by Robotgiggle** [HexxyCraft/modpack#17]
Currently, the packwiz is set up to install version 23.4.0 of Xaero's Minimap and version 1.30.0 of Xaero's World Map. The latest 1.19.2 version of those mods is 23.4.1 and 1.30.1 respectively, so whenever the pack finishes loading it gives a popup suggesting that you update them. However, actually doing so breaks the pack. The next time you boot it up, packwiz doesn't see the versions it's set to install and thus reinstalls them, causing the pack to crash because it finds two versions of the same mod.

**Comment by walksanatora** [comment]
closed with 0170cbb
