### ISSUE TITLE
Add Mediaworks

### ISSUE THREAD

**Issue by Buggy123** [HexxyCraft/modpack#174]
![image](https://github.com/HexxyCraft/modpack/assets/16315400/aacf92fa-1e0e-44d9-9855-8ac4919c68a9)

[Mediaworks](https://modrinth.com/mod/mediaworks)

Hex-casting capes, sorta spectator mode, iota HUDs, trinket media content viewing. Lotsa neat stuff.

**Comment by macks2008** [comment]
[Chloe](https://discord.com/channels/936370934292549712/1101506920268963871/1160262478782017746), myself (as of "sometime this morning"), and possibly other people I'm not specifically aware of, were wondering about the status of this 👀.
