### ISSUE TITLE
Edified Train Tracks are uncraftable

### ISSUE THREAD

**Issue by macks2008** [HexxyCraft/modpack#177]
Create: Steam & Rail's recipe to be incorrectly referring to "hexcasting:edified_slab" as "hexcasting:akashic_slab", but I'm not yet sure if that's the only problem. 
You can assign this one to me. If I get a fix out by tonight, can you expedite it to the release branch? it'll just be a data pack to override the broken recipe, and I was kind of hoping to make some of these rails before the world download if possible.

**Comment by macks2008** [comment]
Where in the file structure should I put data packs?

**Comment by macks2008** [comment]
Fix tested
![image](https://github.com/HexxyCraft/modpack/assets/7110033/8b6364e4-2487-4db0-a9f3-c2b496a5816e)

**Comment by macks2008** [comment]
Judging by beholder's PR to add the milk string recipe, I guess I just merge my pack's data folder into resources?

**Comment by Twisted-Code** [comment]
Ignore the messy force pushing to reword. That is not the commit you're looking for. Move along.
But in any case, there is a PR.
