### ISSUE TITLE
Add config changes from the spreadsheet

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#37]
- [x] Lore fragments datapack
- [x] World reset
- [x] Player menu death count scoreboard
- [x] Worldborder (overworld 2k -> 5k, nether and end start at 5k)
- [x] Update Ancient Scroll loot tables
- [x] Disable using the Hand of Ender on other players

[Spreadsheet](https://docs.google.com/spreadsheets/d/1I50mUijSgFRkGSIz3IKosfJNkVR1Vqqm_1xPUcip-wM/edit)

**Comment by beholderface** [comment]
Wasn't there a decision against KubeJS due to its mixins breaking some other mods on the list?

**Comment by object-Object** [comment]
Yeah looks like it was incompatible with Tinkerer's Smithing. I'll remove that task, thanks.
