### ISSUE TITLE
Adjust Fabrication (I think that's the mod? I can't find the feature in the wiki for it though?) To enable hitting gaurdians with lightning to turn them into 

### ISSUE THREAD

**Issue by FractalineHue** [HexxyCraft/modpack#68]

**Comment by object-Object** [comment]
@LlamaSageR thoughts on this? note the limited worldborder size, though we're expanding to 5k soonish

**Comment by LlamaSageR** [comment]
The change was added via Carpet. From testing, it appears none of them are enabled. Easily enabled though, can be done via command. There's a default file that can be added too, to automatically enable it on all worlds generated via the modpack. Seems that the rest of the Carpet changes also did not make it, so I'll see what I can do to fix that.

**Comment by object-Object** [comment]
Fixed in #99
