### ISSUE TITLE
Duplicate rope recipe

### ISSUE THREAD

**Issue by Pretender8** [HexxyCraft/modpack#70]
There's two different ropes in the pack, each with different crafting recipes. It is possible to merge them into one rope by prioritizing one (ex:supplementaries) over the other and allowing rope to be crafted using either crafting recipe. Could probably be fixed server-side, using a datapack like this as an example:
(Note: for tomato vines, this can be configured to use the Supplementaries rope in-config. However, without the tweak, it will use the rope but then turn into the Farmer's Delight rope when broken.)
[rope_fix.zip](https://github.com/HexxyCraft/modpack/files/11560273/rope_fix.zip)

**Comment by object-Object** [comment]
note - would probably prefer to do it with crafttweaker if only because it's more transparent
