### ISSUE TITLE
Large phial balance discussion

### ISSUE THREAD

**Issue by computer-whisperer** [HexxyCraft/modpack#73]
As-is the only way to craft large phials (>640) is by one of two glitches. The stronger one is by gravestone stacking (creating n graves with one stack of 63 items and picking them up all at once). This glitch has failure modes that can cause the materials to be voided if they are not understood and carefully managed. The server also seems to have a lower success rate at this than single player for some reason.

In theory the grave glitch allows max phials to be generated (~200k media), though I have not verified this empirically yet.

Without inventory stacking , the maximum media quantity you can have on your character is 23040 amethyst dust using charged amethyst or phials generated from said charged amethyst.

A single geode with 40 budding blocks can produce about 4000 amethyst dust per hour w/ silk touch or block dropping and create grinding if I did my math right. Not to mention that geodes spawn with thousands of amethyst dust worth of non-budding blocks.

Something also to note is that future hexcasting versions should have allay quenching which should enable phials of up to 7860 each.

It is my opinion that 640 media phials are far too small for survival media storage given the amethyst production rates that can be easily attained. I was using 10k media mining spells within 24 hours of server start, and even larger spell use is only a matter of time. These spells produce about 2-3 stacks of useful ore blocks each, so I don't consider this media usage to be particularly overpowered for the comparative server time. Doing so required me to fill all but 5 slots of my inventory with amethyst shards.

**Comment by computer-whisperer** [comment]
It is also worth pointing out that there exist other methods for spell use, but they have various drawbacks.

- Wisps can hold large (200k) quantities of media and cast spells for the user. This has several downsides however.
  - https://github.com/Talia-12/Hexal/issues/53 means that travelling through the nether portal while said wisp is alive will cause the wisp to lock up. 
  - Wisps cannot be moved through nether/end portals
  - Using wisps at high cycle rates causes an obnoxious and loud ringing sound on the "player" audio channel. Without high cycle rates the wisp cannot react immediately to RPC based spells.
  - Cannot automatically refuel themselves unless a spell circle and gateways are involved, 

- Spell circles
  - Media stored in an impetus cannot be read, which makes automatic media distribution quite difficult
  - Have a very constrained ambit, and cannot be moved easily
  -

**Comment by Talia-12** [comment]
Next version of Hexal will fix the first two issues with wisps.

**Comment by maraxin** [comment]
As far as I know, with deployer and CC, you can easily make (or even automate) a phial, that has 640> media

**Comment by object-Object** [comment]
Will be fixed in the next update. Added a recipe to merge phials. The inputs must both be full, and the output will be empty with capacity equal to the sum of the inputs. The upper limit is the same as for impetuses (200k dust).
![image](https://github.com/HexxyCraft/modpack/assets/37044997/ae05ed0b-c0b6-42c1-a2fe-1ad276af9462)

**Comment by object-Object** [comment]
Open to input on the balance of this.

**Comment by computer-whisperer** [comment]
Here is the cost progression unless i messed up the math.

Iteration | Phial Size | Total Cost
-- | -- | --
0 | 640 | 640
1 | 1280 | 2560
2 | 2560 | 7680
3 | 5120 | 20480
4 | 10240 | 51200
5 | 20480 | 122880
6 | 40960 | 286720
7 | 81920 | 655360
8 | 163840 | 1474560
9 | 327680 | 3276800

I think this is pretty fair. It would be convenient if trying to merge 2 phials that exceed the limit would cap it to the limit instead of refusing the craft, but it wouldn't be a big deal.

**Comment by object-Object** [comment]
I'd argue that capping it to the limit would be bad because you'd be losing some of the capacity from one of the inputs.
