### ISSUE TITLE
Carpet Functionality Absent

### ISSUE THREAD

**Issue by LlamaSageR** [HexxyCraft/modpack#97]
The functionality Carpet and Carpet-Fixes provide are absent in their entirety. Tested with ``chainStone``, but the others are likely disabled well, including ``renewableDeepslate`` and ``renewableSponges``. Can be enabled on the server via commands, but the settings revert upon restart. The Config needs to be provided in the world folder, and cannot be installed with the modpack itself as far as I know.

**Comment by LlamaSageR** [comment]
Carpet was implemented in issue #40, which was supposed to add the changes discussed in #9. However, the changes are not present. ``renewableDeepslate`` was just tested, and failed as well. I can provide the needed config file, but do not know where to share it.

**Comment by LlamaSageR** [comment]
Issue #68 also stems from this issue.

**Comment by object-Object** [comment]
Apparently the default config is explicitly disabled for servers. Wish that was documented. I'll fix it server-side.
https://github.com/gnembon/fabric-carpet/pull/591
